export const SET_QUIZ_SETTINGS = "SET_QUIZ_SETTINGS";
export const SET_MODAL_OPEN = "SET_MODAL_OPEN";

export const SET_QUESTIONS = "SET_QUESTIONS";
export const SET_ACTIVE_STEP = "SET_ACTIVE_STEP";
export const ADD_ANSWER = "ADD_ANSWER";
export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const SET_ALL_QUESTIONS_ANSWERED = "SET_ALL_QUESTIONS_ANSWERED";
export const RESET_QUESTIONS_INFO = "RESET_QUESTIONS_INFO";

